// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	models "novel-server/shared/models"

	uuid "github.com/google/uuid"
)

// PublishedStoryRepository is an autogenerated mock type for the PublishedStoryRepository type
type PublishedStoryRepository struct {
	mock.Mock
}

// CheckLike provides a mock function with given fields: ctx, userID, storyID
func (_m *PublishedStoryRepository) CheckLike(ctx context.Context, userID uuid.UUID, storyID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, storyID)

	if len(ret) == 0 {
		panic("no return value specified for CheckLike")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID, storyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, storyID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, storyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountActiveGenerationsForUser provides a mock function with given fields: ctx, userID
func (_m *PublishedStoryRepository) CountActiveGenerationsForUser(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveGenerationsForUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, story
func (_m *PublishedStoryRepository) Create(ctx context.Context, story *models.PublishedStory) error {
	ret := _m.Called(ctx, story)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PublishedStory) error); ok {
		r0 = rf(ctx, story)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementLikesCount provides a mock function with given fields: ctx, id
func (_m *PublishedStoryRepository) DecrementLikesCount(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DecrementLikesCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, userID
func (_m *PublishedStoryRepository) Delete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindWithProgressByUserID provides a mock function with given fields: ctx, userID, limit, cursor
func (_m *PublishedStoryRepository) FindWithProgressByUserID(ctx context.Context, userID uuid.UUID, limit int, cursor string) ([]models.PublishedStorySummaryWithProgress, string, error) {
	ret := _m.Called(ctx, userID, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FindWithProgressByUserID")
	}

	var r0 []models.PublishedStorySummaryWithProgress
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string) ([]models.PublishedStorySummaryWithProgress, string, error)); ok {
		return rf(ctx, userID, limit, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string) []models.PublishedStorySummaryWithProgress); ok {
		r0 = rf(ctx, userID, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PublishedStorySummaryWithProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, string) string); ok {
		r1 = rf(ctx, userID, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, string) error); ok {
		r2 = rf(ctx, userID, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PublishedStoryRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.PublishedStory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.PublishedStory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PublishedStory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PublishedStory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PublishedStory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementLikesCount provides a mock function with given fields: ctx, id
func (_m *PublishedStoryRepository) IncrementLikesCount(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementLikesCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsStoryLikedByUser provides a mock function with given fields: ctx, storyID, userID
func (_m *PublishedStoryRepository) IsStoryLikedByUser(ctx context.Context, storyID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, storyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsStoryLikedByUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, storyID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, storyID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, storyID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByIDs provides a mock function with given fields: ctx, ids
func (_m *PublishedStoryRepository) ListByIDs(ctx context.Context, ids []uuid.UUID) ([]*models.PublishedStory, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListByIDs")
	}

	var r0 []*models.PublishedStory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*models.PublishedStory, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*models.PublishedStory); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PublishedStory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserID provides a mock function with given fields: ctx, userID, cursor, limit
func (_m *PublishedStoryRepository) ListByUserID(ctx context.Context, userID uuid.UUID, cursor string, limit int) ([]*models.PublishedStory, string, error) {
	ret := _m.Called(ctx, userID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*models.PublishedStory
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]*models.PublishedStory, string, error)); ok {
		return rf(ctx, userID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []*models.PublishedStory); ok {
		r0 = rf(ctx, userID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PublishedStory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) string); ok {
		r1 = rf(ctx, userID, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int) error); ok {
		r2 = rf(ctx, userID, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListLikedByUser provides a mock function with given fields: ctx, userID, cursor, limit
func (_m *PublishedStoryRepository) ListLikedByUser(ctx context.Context, userID uuid.UUID, cursor string, limit int) ([]*models.PublishedStory, string, error) {
	ret := _m.Called(ctx, userID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListLikedByUser")
	}

	var r0 []*models.PublishedStory
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]*models.PublishedStory, string, error)); ok {
		return rf(ctx, userID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []*models.PublishedStory); ok {
		r0 = rf(ctx, userID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PublishedStory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) string); ok {
		r1 = rf(ctx, userID, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int) error); ok {
		r2 = rf(ctx, userID, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListPublic provides a mock function with given fields: ctx, cursor, limit
func (_m *PublishedStoryRepository) ListPublic(ctx context.Context, cursor string, limit int) ([]*models.PublishedStory, string, error) {
	ret := _m.Called(ctx, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPublic")
	}

	var r0 []*models.PublishedStory
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*models.PublishedStory, string, error)); ok {
		return rf(ctx, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*models.PublishedStory); ok {
		r0 = rf(ctx, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PublishedStory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) string); ok {
		r1 = rf(ctx, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = rf(ctx, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkStoryAsLiked provides a mock function with given fields: ctx, storyID, userID
func (_m *PublishedStoryRepository) MarkStoryAsLiked(ctx context.Context, storyID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, storyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkStoryAsLiked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, storyID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkStoryAsUnliked provides a mock function with given fields: ctx, storyID, userID
func (_m *PublishedStoryRepository) MarkStoryAsUnliked(ctx context.Context, storyID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, storyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkStoryAsUnliked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, storyID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPublic provides a mock function with given fields: ctx, id, userID, isPublic
func (_m *PublishedStoryRepository) SetPublic(ctx context.Context, id uuid.UUID, userID uuid.UUID, isPublic bool) error {
	ret := _m.Called(ctx, id, userID, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for SetPublic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, userID, isPublic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConfigAndSetup provides a mock function with given fields: ctx, id, config, setup
func (_m *PublishedStoryRepository) UpdateConfigAndSetup(ctx context.Context, id uuid.UUID, config []byte, setup []byte) error {
	ret := _m.Called(ctx, id, config, setup)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfigAndSetup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, []byte) error); ok {
		r0 = rf(ctx, id, config, setup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConfigAndSetupAndStatus provides a mock function with given fields: ctx, id, config, setup, status
func (_m *PublishedStoryRepository) UpdateConfigAndSetupAndStatus(ctx context.Context, id uuid.UUID, config json.RawMessage, setup json.RawMessage, status models.StoryStatus) error {
	ret := _m.Called(ctx, id, config, setup, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfigAndSetupAndStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, json.RawMessage, json.RawMessage, models.StoryStatus) error); ok {
		r0 = rf(ctx, id, config, setup, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusDetails provides a mock function with given fields: ctx, id, status, setup, title, description, errorDetails
func (_m *PublishedStoryRepository) UpdateStatusDetails(ctx context.Context, id uuid.UUID, status models.StoryStatus, setup json.RawMessage, title *string, description *string, errorDetails *string) error {
	ret := _m.Called(ctx, id, status, setup, title, description, errorDetails)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.StoryStatus, json.RawMessage, *string, *string, *string) error); ok {
		r0 = rf(ctx, id, status, setup, title, description, errorDetails)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVisibility provides a mock function with given fields: ctx, storyID, userID, isPublic
func (_m *PublishedStoryRepository) UpdateVisibility(ctx context.Context, storyID uuid.UUID, userID uuid.UUID, isPublic bool) error {
	ret := _m.Called(ctx, storyID, userID, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVisibility")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, storyID, userID, isPublic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPublishedStoryRepository creates a new instance of PublishedStoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublishedStoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublishedStoryRepository {
	mock := &PublishedStoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
