// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

// GenerateInterServiceToken provides a mock function with given fields: issuer, subject, ttl
func (_m *TokenGenerator) GenerateInterServiceToken(issuer string, subject string, ttl time.Duration) (string, error) {
	ret := _m.Called(issuer, subject, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateInterServiceToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) (string, error)); ok {
		return rf(issuer, subject, ttl)
	}
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) string); ok {
		r0 = rf(issuer, subject, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, time.Duration) error); ok {
		r1 = rf(issuer, subject, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateToken provides a mock function with given fields: userID, roles, ttl
func (_m *TokenGenerator) GenerateToken(userID uint64, roles []string, ttl time.Duration) (string, error) {
	ret := _m.Called(userID, roles, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, []string, time.Duration) (string, error)); ok {
		return rf(userID, roles, ttl)
	}
	if rf, ok := ret.Get(0).(func(uint64, []string, time.Duration) string); ok {
		r0 = rf(userID, roles, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint64, []string, time.Duration) error); ok {
		r1 = rf(userID, roles, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
