package interfaces

import (
	"context"
	"novel-server/shared/models"

	"github.com/google/uuid"
)

// StorySceneRepository defines the interface for interacting with story scene data.
//
//go:generate mockery --name StorySceneRepository --output ./mocks --outpkg mocks --case=underscore
type StorySceneRepository interface {
	// Create inserts a new story scene record.
	// Used when a new scene is generated by the AI.
	Create(ctx context.Context, scene *models.StoryScene) error

	// FindByStoryAndHash attempts to find an existing scene for a given story
	// based on the state hash that led to it. Returns ErrNotFound if no scene exists.
	FindByStoryAndHash(ctx context.Context, publishedStoryID uuid.UUID, stateHash string) (*models.StoryScene, error)

	// GetByID retrieves a story scene by its unique ID.
	// Returns models.ErrNotFound if the scene is not found.
	GetByID(ctx context.Context, id uuid.UUID) (*models.StoryScene, error)

	// GetByStoryIDAndStateHash retrieves a story scene by its story ID and state hash.
	// Returns models.ErrNotFound if the scene is not found.
	GetByStoryIDAndStateHash(ctx context.Context, storyID uuid.UUID, stateHash string) (*models.StoryScene, error)

	// ListByStoryID retrieves all scenes for a given story.
	// Returns models.ErrNotFound if no scenes exist for the story.
	ListByStoryID(ctx context.Context, storyID uuid.UUID) ([]models.StoryScene, error)

	// UpdateContent updates the content of a story scene.
	UpdateContent(ctx context.Context, id uuid.UUID, content []byte) error

	// Upsert creates a new scene or updates an existing one based on storyID and stateHash.
	Upsert(ctx context.Context, scene *models.StoryScene) error

	// Delete deletes a story scene by its ID.
	Delete(ctx context.Context, id uuid.UUID) error
}
