x-environment-defaults: &env-vars
  ENV: ${ENV:-development}
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DB_HOST: ${DB_HOST:-localhost}
  DB_PORT: ${DB_PORT:-5432}
  DB_USER: ${DB_USER:-postgres}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME:-novel_db}
  DB_SSL_MODE: ${DB_SSL_MODE:-disable}
  REDIS_ADDR: ${REDIS_ADDR:-localhost:6379}
  REDIS_PASSWORD: ${REDIS_PASSWORD:-}
  REDIS_DB: ${REDIS_DB:-0}
  JWT_SECRET: ${JWT_SECRET}
  PASSWORD_SALT: ${PASSWORD_SALT}
  JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL:-15m}
  JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL:-168h}
  SERVICE_ID: ${SERVICE_ID:-default-service}
  INTER_SERVICE_SECRET: ${INTER_SERVICE_SECRET}
  INTER_SERVICE_TTL: ${INTER_SERVICE_TTL:-5m}
  AI_API_KEY: ${AI_API_KEY}
  RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/}

services:
  # API Gateway (Traefik)
  api-gateway:
    image: traefik:v2.11 # Используем стабильную версию Traefik
    container_name: novel_api_gateway
    command:
      # Включаем Docker провайдер
      - "--providers.docker=true"
      # Не разрешаем Traefik обнаруживать контейнеры без явной метки traefik.enable=true
      - "--providers.docker.exposedbydefault=false"
      # Определяем точку входа 'web' на порту 8080 (для пользовательского трафика)
      - "--entrypoints.web.address=:8080"
      # Определяем точку входа 'traefik' (для API/Dashboard) на порту 8081
      - "--entrypoints.traefik.address=:8081"
      # Включаем API Traefik и Dashboard, указывая, что они должны использовать точку входа 'traefik'
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true" # В продакшене защитить!
      # Включаем логирование доступа
      - "--accesslog=true"
      # Указываем уровень логов Traefik
      - "--log.level=INFO" # Или DEBUG для отладки
    ports:
      # Публикуем порт 8080 (хост) -> 8080 (контейнер, entrypoint 'web')
      - "8080:8080"
      # Публикуем порт 8888 (хост) -> 8081 (контейнер, entrypoint 'traefik' для API/Dashboard)
      - "8888:8081"
    volumes:
      # Монтируем Docker сокет, чтобы Traefik мог слушать события Docker
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # Можно добавить depends_on, если нужно дождаться старта других сервисов, но обычно Traefik сам справляется

  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: novel_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-novel_db}
    ports:
      # Порт публикуется только для локального доступа к БД, если нужно
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-novel_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Кэш Redis
  redis:
    image: redis:7-alpine
    container_name: novel_redis
    ports:
      # Порт публикуется только для локального доступа к Redis, если нужно
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис миграций (запускается перед auth)
  migrate:
    build:
      context: .
      dockerfile: deploy/docker/migrate/Dockerfile
    container_name: novel_migrate
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER:-postgres}:${DB_PASSWORD}@postgres:5432/${DB_NAME:-novel_db}?sslmode=${DB_SSL_MODE:-disable}",
      "up"
    ]

  # Сервис авторизации
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: novel_auth
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
         condition: service_completed_successfully
    environment:
      <<: *env-vars
      DB_HOST: postgres # Внутреннее имя хоста БД
      REDIS_ADDR: redis:6379 # Внутренний адрес Redis
      SERVER_PORT: ${AUTH_SERVER_PORT:-8081} # Внутренний порт сервиса
      SERVICE_ID: auth-service
    # ports: # Убираем публикацию порта наружу
    #   - "${AUTH_SERVER_PORT:-8081}:${AUTH_SERVER_PORT:-8081}"
    labels:
      # Включаем Traefik для этого сервиса
      - "traefik.enable=true"
      # Определяем роутер для HTTP запросов к auth
      - "traefik.http.routers.auth-http.rule=PathPrefix(`/api/auth`)" # Все пути, начинающиеся с /api/auth
      - "traefik.http.routers.auth-http.entrypoints=web" # Используем точку входа 'web' (порт 8080)
      # Указываем, на какой внутренний порт Traefik должен перенаправлять трафик
      - "traefik.http.services.auth-service.loadbalancer.server.port=${AUTH_SERVER_PORT:-8081}"
      # Middleware для удаления префикса /api/auth перед отправкой запроса в сервис auth
      # Сервис auth ожидает запросы на /register, /login и т.д., а не /api/auth/register
      - "traefik.http.routers.auth-http.middlewares=auth-stripprefix"
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/api/auth"

  # Сервис Геймплея (обработка запросов /api/stories)
  gameplay-service:
    build:
      context: .
      dockerfile: gameplay-service/Dockerfile
    container_name: novel_gameplay_service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate:
         condition: service_completed_successfully
    environment:
      <<: *env-vars # Наследуем общие переменные
      DB_HOST: postgres # Внутреннее имя хоста БД
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/ # URL для Docker
      SERVER_PORT: ${GAMEPLAY_SERVER_PORT:-8082} # Внутренний порт сервиса
      SERVICE_ID: gameplay-service
      # JWT_SECRET уже включен через *env-vars
    # ports: # Убираем публикацию порта наружу
    #   - "${GAMEPLAY_SERVER_PORT:-8082}:${GAMEPLAY_SERVER_PORT:-8082}"
    labels:
      # Включаем Traefik для этого сервиса
      - "traefik.enable=true"
      # Определяем роутер для HTTP запросов к gameplay
      - "traefik.http.routers.gameplay-http.rule=PathPrefix(`/api/stories`)" # Все пути, начинающиеся с /api/stories
      - "traefik.http.routers.gameplay-http.entrypoints=web" # Используем точку входа 'web' (порт 8080)
      # Указываем, на какой внутренний порт Traefik должен перенаправлять трафик
      - "traefik.http.services.gameplay-service.loadbalancer.server.port=${GAMEPLAY_SERVER_PORT:-8082}"
      # Middleware для удаления префикса /api/stories перед отправкой запроса в сервис gameplay
      - "traefik.http.routers.gameplay-http.middlewares=gameplay-stripprefix"
      - "traefik.http.middlewares.gameplay-stripprefix.stripprefix.prefixes=/api/stories"

  # Сервис RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: novel_rabbitmq
    ports:
      # Порты для доступа извне (если нужно) и для Management UI
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGE_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис Story Generator
  story-generator:
    build:
      context: .
      dockerfile: story-generator/Dockerfile
    container_name: novel_story_generator
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./promts:/app/promts
    environment:
      <<: *env-vars
      DB_HOST: postgres
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
      PROMPTS_DIR: /app/promts
      SERVICE_ID: story-generator-service
    # Этот сервис не обрабатывает внешние HTTP запросы, поэтому не нуждается в метках Traefik

  # Сервис WebSocket уведомлений
  websocket-service:
    build:
      context: .
      dockerfile: websocket-service/Dockerfile
    container_name: novel_websocket_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      # auth сервис не обязателен для *запуска* websocket-service,
      # но нужен для валидации токенов при установке соединения.
      # depends_on auth не требуется, если auth стартует быстро.
    environment:
      <<: *env-vars # Наследуем общие переменные
      PORT: ${WEBSOCKET_SERVER_PORT:-8083} # Внутренний порт сервиса
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/ # URL для Docker
      SERVICE_ID: websocket-service
      # JWT_SECRET уже включен через *env-vars
    # ports: # Убираем публикацию порта наружу
    #   - "${WEBSOCKET_SERVER_PORT:-8083}:${WEBSOCKET_SERVER_PORT:-8083}"
    labels:
      # Включаем Traefik для этого сервиса
      - "traefik.enable=true"
      # Определяем роутер для WebSocket запросов
      # Используем Path(`/ws`) для точного совпадения пути
      - "traefik.http.routers.websocket-ws.rule=Path(`/ws`)"
      - "traefik.http.routers.websocket-ws.entrypoints=web" # Используем точку входа 'web' (порт 8080)
      # Указываем внутренний порт сервиса
      - "traefik.http.services.websocket-service.loadbalancer.server.port=${WEBSOCKET_SERVER_PORT:-8083}"
      # Для WebSocket не нужен stripprefix, т.к. сервис ожидает запрос на /ws

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  # Добавляем том для данных Traefik (если нужно хранить SSL сертификаты и т.д.)
  # traefik_data:

# Можно определить внешние сети, если необходимо
# networks:
#   default:
#     driver: bridge
