global:
  scrape_interval: 15s # Интервал опроса по умолчанию

scrape_configs:
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:9094'] # Используем имя сервиса и НОВЫЙ порт метрик 9094

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081'] # Используем имя сервиса и его порт

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419'] # Используем имя сервиса и его порт

  - job_name: 'traefik' # Новая задача для сбора метрик с Traefik
    static_configs:
      - targets: ['api-gateway:8081'] # Используем имя сервиса и порт, указанный в entryPoint metrics
    metrics_path: /metrics # Указываем путь к метрикам (хотя /metrics по умолчанию)

  - job_name: 'websocket-service' # Новая задача для WebSocket сервиса
    static_configs:
      - targets: ['websocket-service:9092'] # Используем имя сервиса и порт метрик

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true 