# traefik_dynamic.yml
http:
  # ============================================
  # Middlewares
  # ============================================
  middlewares:
    # --- Strip Prefixes ---
    auth-stripprefix:
      stripPrefix:
        prefixes:
          - "/api"

    # Убирает /api/stories перед отправкой запроса в gameplay-service
    gameplay-stripprefix:
      stripPrefix:
        prefixes:
          - "/api"

    # Убирает /admin перед отправкой запроса в admin-service (для защищенных путей)
    admin-protected-stripprefix:
      stripPrefix:
        prefixes:
          - "/admin"

  # ============================================
  # Routers
  # ============================================
  routers:
    # --- Landing Page Router (Lowest priority catch-all for non-API routes) ---
    landing-page-router:
      entryPoints:
        - "web"
      # Matches paths NOT starting with known API/service prefixes
      rule: "!PathPrefix(`/api`, `/admin`, `/login`, `/ws`)"
      service: "landing-page-service"
      priority: 1 # Low priority ensures API routes match first

    # --- Auth Service (Single Router for all /api/*) ---
    auth-router:
      entryPoints:
        - "web"
      rule: "PathPrefix(`/api`)"
      service: "auth-service"
      middlewares:
        - "auth-stripprefix"
      priority: 10

    # --- Gameplay Service ---
    gameplay-http-router:
      entryPoints:
        - "web"
      # Matches either path prefix
      rule: "(PathPrefix(`/api/stories`) || PathPrefix(`/api/published-stories`))"
      service: "gameplay-service"
      middlewares:
       - "gameplay-stripprefix"
      priority: 11 # Higher priority for API routes

    # --- Admin Service (Login Page) ---
    admin-login-router:
      entryPoints:
        - "web"
      # Matches exact path
      rule: "Path(`/login`)"
      service: "admin-service"
      priority: 11 # Higher priority for exact path

    # --- Admin Service (Protected Routes) ---
    admin-protected-router:
      entryPoints:
        - "web"
      # Matches path prefix
      rule: "PathPrefix(`/admin`)"
      service: "admin-service"
      middlewares:
        - "admin-protected-stripprefix"
      priority: 10 # Higher priority for API routes

    # --- Websocket Service ---
    websocket-router:
      entryPoints:
        - "web"
      # Matches exact path
      rule: "Path(`/ws`)"
      service: "websocket-service"
      priority: 11 # Higher priority for exact path

    # <<< ДОБАВЛЕНО: Роутер для Image Server >>>
    image-server-router:
      entryPoints:
        - "web"
      rule: "PathPrefix(`/generated-images`)" # Маршрут для статики
      service: "image-server-service"
      priority: 10 # Приоритет как у других сервисов API

  # ============================================
  # Services (Load Balancers)
  # ============================================
  services:
    # --- Landing Page Service ---
    landing-page-service:
      loadBalancer:
        servers:
          - url: "http://landing-page:80" # Nginx listens on port 80

    # --- Auth Service ---
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8081"

    # --- Gameplay Service ---
    gameplay-service:
      loadBalancer:
        servers:
          - url: "http://gameplay-service:8082"

    # --- Admin Service ---
    admin-service:
      loadBalancer:
        servers:
          - url: "http://admin-service:8084"

    # --- Websocket Service ---
    websocket-service:
      loadBalancer:
        servers:
          - url: "http://websocket-service:8083"

    # <<< ДОБАВЛЕНО: Сервис для Image Server (Nginx) >>>
    image-server-service:
      loadBalancer:
        servers:
          - url: "http://image-server:80" # Nginx внутри контейнера слушает порт 80