basePath: /ws
host: localhost:8083
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Real-time уведомления для Novel Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Novel Server WebSocket API
  version: "1.0"
paths:
  /health:
    get:
      description: Возвращает статус работы WebSocket Service
      produces:
      - application/json
      responses:
        "200":
          description: Сервис работает
          schema:
            additionalProperties: true
            type: object
      summary: Проверка состояния сервиса
      tags:
      - health
  /ws:
    get:
      description: Устанавливает WebSocket соединение для real-time уведомлений
      parameters:
      - description: JWT токен для аутентификации
        in: query
        name: token
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
        "400":
          description: Неверные параметры
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Неавторизован
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: WebSocket соединение
      tags:
      - websocket
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
