// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	messaging "novel-server/gameplay-service/internal/messaging"

	mock "github.com/stretchr/testify/mock"
)

// ClientUpdatePublisher is an autogenerated mock type for the ClientUpdatePublisher type
type ClientUpdatePublisher struct {
	mock.Mock
}

// PublishClientUpdate provides a mock function with given fields: ctx, payload
func (_m *ClientUpdatePublisher) PublishClientUpdate(ctx context.Context, payload messaging.ClientStoryUpdate) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishClientUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, messaging.ClientStoryUpdate) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientUpdatePublisher creates a new instance of ClientUpdatePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientUpdatePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientUpdatePublisher {
	mock := &ClientUpdatePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
